### ISSUE TITLE
Files not loading

### ISSUE THREAD

**Issue by muhammad-kabir** [kimlimjustin/xplorer#46]
**Describe the bug**
I don't if it's even a bug, or just human error, but I downloaded it, and it opened, but it's yet to load any files. 

**To Reproduce**
1. Head to the xplorer GitHub page
2. Download  Xplorer-Setup-0.1.0.exe
3. Run the file and install the app
4. Open the app

**Expected behavior**
Load up all my files, as a file explorer should, in a timely manner. 

**Screenshots**
This are my specs, if it's necessary.
![InkedApplicationFrameHost_LJGNWTU5R6_LI](https://user-images.githubusercontent.com/90667776/134795565-e43f198c-2ac1-4c8b-afdb-4cab9ce74d42.jpg)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Home Ver. 10.0.19043 Build 19043
 - App Version: 0.1.0 (if I'm going by the xplorer setup

**Additional comment**
Even after restarting, it still hasn't loaded any files. I've closed and opened the app, even reinstalled it. Hopefully it's just human error, cos it looks super sick and I wanna be able to use it properly.

**Comment by kimlimjustin** [comment]
Erm, could you please screenshot what showing up when you open xplorer? Xplorer will show you the Home page of Xplorer, containing the basic Documents, Downloads etc folder navigation if Xplorer works as expected.

**Comment by muhammad-kabir** [comment]
Sorry, idk why that slipped my mind 

Here it is:
![Xplorer_gqbbyRRXPf](https://user-images.githubusercontent.com/90667776/134814510-687854f8-f250-4f2b-94de-c3850c7ed421.png)
.

**Comment by kimlimjustin** [comment]
Could you please type `Ctrl + Shift + I` and navigate into the `Console` (Just the same as Chrome devtool) and see if there's any error?

**Comment by muhammad-kabir** [comment]
Here it is: 

![Xplorer_gqbbyRRXPf](https://user-images.githubusercontent.com/90667776/134816527-4b3789d0-a557-4d01-8b05-052582b442b3.png)

**Comment by rushabh-wadkar** [comment]
@kimlimjustin 

> wmic is the program, which will enable access to Windows Management Instrumentation console and nodeagent will require access to that program for getting CPU and Memory usage in the machine. Current issue will occur when wmi​c program is not present in the system PATH environment variable.

@muhammad-kabir can you try the steps given on [this](https://superuser.com/questions/1178674/wmic-is-not-recognized-as-an-internal-or-external-command-operable-program-or) or [this](https://knowledge.informatica.com/s/article/156865?language=en_US)

**Comment by Ahmed-Elrayes** [comment]
same thing goes for me, here is a screenshot of the console.
idk why it says something about vscode, i don't use it at all
![Image 3](https://user-images.githubusercontent.com/30704271/134827253-427ddc37-cfe8-4eeb-9922-e3b6659b536a.png)

**Comment by kimlimjustin** [comment]
You can actually safely ignore the VScode log, the problem should go to the console.error which failed to find documents folder, Ill take a look into it

**Comment by kimlimjustin** [comment]
Eh I just comment that and you edited your comment haha, does it working now?

**Comment by Ahmed-Elrayes** [comment]
yeah it was because of windows defender, i totally forgot about it, i hope you can add in the readme file that people should allow it to access the documents folder from windows defender.
and yeah it's working perfectly now, i wanna know how to edit it because i wanna change font size and the effect that happens when you hover on a folder/file..

**Comment by kimlimjustin** [comment]
Thanks for your confirmation, will at it into the docs together with the wmic problem soon.

For the font size, actually this is the theme customization section, which not done yet at the time 0.1.0 release (still working on it now tho, almost finish), stay tuned for the next version

For the hover effect, there's already an issue there which describe the problem (I'll work on that issue). For now, I think you can try change the layout maybe.

Really sorry for your inconvenience. I'll try my best to make it better, thanks :)

**Comment by Ahmed-Elrayes** [comment]
it's okay, it is a really cool application which is so great, thanks for your hard work because you've really made an amazing working using only type script.
unfortunately i'm not good at JS/TypeScript i only know basic stuff. but it's really great to have something different, i guess all what you need to do is to try to make it more stable since i can feel some lag in it, also when i right click on any file and click on properties it only shows the file data, but i guess it would be better to make a menu like normal windows explorer so that people can rename, change file attributes like hide ..etc 

in the end i wanna say, Really thanks for your HUGE EFFORT, you've done something so great.♥

**Comment by Ahmed-Elrayes** [comment]
Btw, i wanted to say something more, thank god that chrome has this discover feature, that is how i knew about this amazing app
![Screenshot_2021-09-27-01-37-39-566_com android chrome](https://user-images.githubusercontent.com/30704271/134828188-66ad78ab-4669-4ef9-894c-0ac91cd4764c.jpg)

**Comment by kimlimjustin** [comment]
Thanks for your feedback! The context menu (right-click items) will definitely be refactored as soon as possible (together with the plugin).
I don't even know that my blog appeared on google lmao. I was just writing docs with the hope to bring a bit of popularity of Xplorer (I don't even know that's this many, I was just hoping for like 50 stars or so, and now it's 380 :D and my blog reaches almost 30 thousand views). Thank god

**Comment by Ahmed-Elrayes** [comment]
well maybe because i used to see stuff in DEV Community so it shows me stuff like these, i always check this list on chrome daily, and yeah it worth it.

**Comment by kimlimjustin** [comment]
Oh okay, thanks!

**Comment by ChiBear** [comment]
Hi, writing from alt GitHub account of @muhammad-kabir 

Thanks to @rushabh-wadkar for this link: https://superuser.com/questions/1178674/wmic-is-not-recognized-as-an-internal-or-external-command-operable-program-or

It worked to get xplorer working, but now I'm faced with a new issue:

![Xplorer_pUfTzL3qUp](https://user-images.githubusercontent.com/46738268/134837465-08074b04-008e-47f1-8a4e-12e6f9f52618.png)

As you can see, this is my main screen. If I press on Documents or Windows-SSD (C:), it shows this:

![Xplorer_rEEVJdik9k](https://user-images.githubusercontent.com/46738268/134837556-a4f64c5f-c6d6-48ff-b6eb-44116edb23ad.png)

I assume these are the items loading in, but even after some time (way more than I would consider reasonable), it's still as shown in the screenshot.

The other items in the sidebar work just fine though.

I've also noticed that xplorer takes a fair bit of CPU, as shown here:

![Taskmgr_2aTMDfK6QE](https://user-images.githubusercontent.com/46738268/134837813-be680182-05cb-4ffe-9db3-a81c716e8d65.png)

Is this part of the issue, or is this supposed to be normal? 

Otherwise, I like the overall look of the application. Maybe some simple animations (such as making the dropdown arrows visibly rotate and giving the dropping items some bounce) could go to making a more seamless and 'professional' experience. I would also recommend closing the context menu after pressing 'Pin to Sidebar' (or at least change it to say 'Unpin from Sidebar', since the functionality seems to change as well).

I hope to see this application improve and become something amazing!

**Comment by kimlimjustin** [comment]
> Is this part of the issue, or is this supposed to be normal?

After installing, close it and open it again, the CPU usage will drop (It's taking about 1 - 5 % on my computer) (I know this is quite big because Xplorer is built on Electron, I'll try my best to decrease it. )
Also, the CPU will go higher if you open a big directory, but I don't think will take too much except you enable the preview video option on setting)

For the animations, I'm still working on it :) Stay tuned for the next version (next month maybe)

**Comment by ChiBear** [comment]
Oh, yea the usage has gone down. Thanks!

That still doesn't explain why drive and downloads result in that second screenshot shown, though.

Also, when I open the settings, I can't seem to close the settings, the arrow doesn't work and I have to reload the entire app lol.

Generally, I find this app to have a lot of potential, but there some things I do wanna say:

One thing I'm used to in the default windows file explorer that isn't present here is mouse thumb button support. I use those a lot to navigate back and forth, and implementation of such a feature would be great. 

To make it stand out from the default file explorer, the implementation of features such as previewing of certain files (such as images or word docs) in the explorer itself would be good. 

For now, I'll stick to the default windows file explorer, but I'll be eyeing this project, and I hope this application can become as good as I think it can be!

**Comment by kimlimjustin** [comment]
> That still doesn't explain why drive and downloads result in that second screenshot shown, though.

Ah sorry, I accidentally skipped this, is it only in the downloads folder? for the drive, is every drive went like that? the downloads folder is probably because of the OneDrive (Not supported yet)

> One thing I'm used to in the default windows file explorer that isn't present here is mouse thumb button support. I use those a lot to navigate back and forth, and implementation of such a feature would be great.

Ye, there's already an issue that addressing this (#58) , still learning how to implement such feature.

> For now, I'll stick to the default windows file explorer, but I'll be eyeing this project, and I hope this application can become as good as I think it can be!

Thanks! Xplorer is just pre-release here, not even stable, I'll try my best to make it stable and hopefully, everything works on the 1.0.0 release in the future.

**Comment by ChiBear** [comment]
> Ah sorry, I accidentally skipped this, is it only in the downloads folder? for the drive, is every drive went like that? the downloads folder is probably because of the OneDrive (Not supported yet)

I only have one drive, as shown in the screenshot. And isn't the Downloads folder supposed to be local? It's the folder in which I store downloads from browsers and whatnot. 

> Ye, there's already an issue that addressing this (#58) , still learning how to implement such feature.

Ah, that's fair. Good luck with that!

> Thanks! Xplorer is just pre-release here, not even stable, I'll try my best to make it stable and hopefully, everything works on the 1.0.0 release in the future.

All the best on your endeavors, bro.

**Comment by kimlimjustin** [comment]
> I only have one drive, as shown in the screenshot. 

Erm, IDK why is this, but probably because of some protected folder, I'll refactor the code and add an exception handler.

> And isn't the Downloads folder supposed to be local? It's the folder in which I store downloads from browsers and whatnot.

I know it's quite weird but it's could be the case. 

To certain about what happens, could you please type `Ctrl + Shift + I` and navigate to the `console` section (just like the chrome devtool) and see what's the error?

**Comment by ChiBear** [comment]
Oh wait now it's fine???

I left for lunch and left the com on for like an hour and now it's fine lol

The downloads file freezes a bit before opening but it opens now.

Now that I've gotten a better opportunity to try it out, here are some preliminary observations of the application:

1.  In detail view, the animation when hovering is cool, but a bit excessive. An option to turn them down in settings would be much appreciated.

2. For the context menu, the popup menus (i.e. the Sort By popup) can't be navigated to. I open up the context menu, try to use the Sort By, but it closes the popup even if it should be on the first item in the popup.

3. The settings menu can't be closed even after it's been opened, even after pressing the arrow. I have reload the application after I'm done with the settings.

4. Maybe a bit more of a personal thing, but I like the way the default Windows File Explorer does its Downloads section (i.e. section it by certain time periods, such as Yesterday, Last Week and so on). It's not a super big priority, but it would be nice to see it available.

5. I think having a new folder icon to press would be useful personally, because I don't really use the shortcut or the context menu to create a folder too often.

Feel free to take all or none of my opinions/ observations into consideration. 

All the best :)

**Comment by kimlimjustin** [comment]
> In detail view, the animation when hovering is cool, but a bit excessive. An option to turn them down in settings would be much appreciated.
This has been addressed as an issue. (#50)

> For the context menu, the popup menus (i.e. the Sort By popup) can't be navigated to. I open up the context menu, try to use the Sort By, but it closes the popup even if it should be on the first item in the popup.

For now, you can show the submenu by clicking the menu once. However, enhancement for the ability of keep the submenu opens on hover is also addressed (#48 

> The settings menu can't be closed even after it's been opened, even after pressing the arrow. I have reload the application after I'm done with the settings.

A fixed delivered at #63, stay tuned for next version!

> Maybe a bit more of a personal thing, but I like the way the default Windows File Explorer does its Downloads section (i.e. section it by certain time periods, such as Yesterday, Last Week and so on). It's not a super big priority, but it would be nice to see it available.

Added into the todo list of the [project](https://github.com/kimlimjustin/xplorer/projects/1)

> I think having a new folder icon to press would be useful personally, because I don't really use the shortcut or the context menu to create a folder too often.

Added into the to-do list too!

Thank you very much!

**Comment by ChiBear** [comment]
Wow! Good going man

If only I was as hardworking as you haha

I'll be keeping tabs on this project with great interest :)

**Comment by kimlimjustin** [comment]
Thanks haha
