### ISSUE TITLE
Add Author metdata in exe file

### ISSUE THREAD

**Issue by codewithpom** [kimlimjustin/xplorer#53]
The problem is that when I download the exe file it shows that it is dangerous but still i install it and I want to suggest that add a publisher name is it so that it will not look dangerous to the system

**Comment by kimlimjustin** [comment]
> The problem is that when I download the exe file it shows that it is dangerous but still i install it and I want to suggest that add a publisher name is it so that it will not look dangerous to the system

I actually knew this problem before, but the after check the documentation of `electron-builder`, it's not the problem of the author, since the author is written there (you can check it by opening the control panel and navigate into Programs and Features, there is the publisher).
![image](https://user-images.githubusercontent.com/61906684/134809242-e087c6c5-a827-4889-8b3e-c45a3ecf7076.png)

The problem is, I should sign the app by buying a certificate (https://www.electron.build/code-signing.html#windows) which I can't afford as a student, and I looked into another alternative, to register the app into Microsoft store, but it also requires me to pay which I can't afford too.

That's why I write the guide to handle this on the docs. (https://xplorer.vercel.app/docs/install/#common-problems)

**Comment by codewithpom** [comment]
oh No problem I was just saying but I have one more issue that it does not open even when I see it's processes running in task manager

**Comment by kimlimjustin** [comment]
> oh No problem I was just saying but I have one more issue that it does not open even when I see it's processes running in task manager

Try killing it and open it again, does it still not opening? If yes, please open an new issue

**Comment by codewithpom** [comment]
It still does not work even when I have vscode latest version  but it not even opens vscode and I have 6 GB RAM and vscode latest version can you please check this

**Comment by kimlimjustin** [comment]
Wait do you mean that `Open in VSCode` not working, I think you can just specify it on a new issue?

**Comment by codewithpom** [comment]
No vscode is working even from command line.

**Comment by kimlimjustin** [comment]
Wait, I don't get what do you mean? Are you complaining about `Open in VSCode` feature of Xplorer not working?
![image](https://user-images.githubusercontent.com/61906684/134859282-7579e13b-c3b7-484b-b600-8fe92d1d1d76.png)

Or do you mean you are building Xplorer from source from the terminal?

**Comment by codewithpom** [comment]
no I am saying that xplorer is not working and in a issue on xplorer you said that if vscode works then even it should work but not even the xplorer is opening .

**Comment by kimlimjustin** [comment]
> no I am saying that xplorer is not working and in a issue on xplorer you said that if vscode works then even it should work but not even the xplorer is opening .

What I meant is if you can **even** run VSCode, then Xplorer should works, not saying if Xplorer work VSCode should works, it's two different things.

**Comment by codewithpom** [comment]
ok but what should I do now I want to try it :frowning:
