### ISSUE TITLE
Bunch of reports and suggestions

### ISSUE THREAD

**Issue by Inflactwf** [kimlimjustin/xplorer#54]
Hello, i have found few bugs and also want to see how you react on suggestions that i have.
Bugs:
1. If you open Properties of some folder or file and then close, the information label wont disappear. It moves outside of the edge but stays still visible and you can't move or close it on your own. (screenshot 1)
2. The program starts being slow after some time, like 5 or 10 minutes, especially if you open concurrently few tabs and use them. You can see that if you open Settings or click some files. The problem affects only animations i guess, because it doesn't decrease performance (or may be i'm wrong, not sure).

Suggestions:
1. Add to context menu all the applications that default Windows has, because most of them are useful and this is a big restriction for users.

If i remember more, i'll add. Thanks.
OS: Windows 10 21H1 19043.1237

**Comment by kimlimjustin** [comment]
> If you open Properties of some folder or file and then close, the information label wont disappear. It moves outside of the edge but stays still visible and you can't move or close it on your own. (screenshot 1)

I just realized this after releasing it, so sorry for this. I'll refactor it together with other functions (context menu, rename popup, and the properties), and also will add native code to get more properties of a file. 

> The program starts being slow after some time, like 5 or 10 minutes, especially if you open concurrently few tabs and use them. You can see that if you open Settings or click some files. The problem affects only animations i guess, because it doesn't decrease performance (or may be i'm wrong, not sure).

Erm, this is maybe because of the memory consumes by Electron and JavaScript. I'm still learning about it and try my best to fix it. For the performance, I think some of the functions that are executed on the JavaScript function will be affected more or less, but for functions like copy files, I don't think it will be affected.

> Add to context menu all the applications that default Windows has, because most of them are useful and this is a big restriction for users.

Yap, I'm still learning the registry on Windows.

Thanks for your suggestion and I apologize for your inconvenience. I will try my best to improve Xplorer. I'm sorry if I can't fix it really soon but I'll try my best ASAP, since I'm currently working on the theme customization and I also got school.

**Comment by kimlimjustin** [comment]
Fixed in master
