### ISSUE TITLE
Moving window across screen is very laggy

### ISSUE THREAD

**Issue by Profesor08** [kimlimjustin/xplorer#66]
**Describe the bug**
When I move window, it not moving as normal window.

**To Reproduce**
Try to move

**Sugestion**
Remove you implementation. And replace just with one line of css code for desired element, to make window moving if you try to drag this element.
`-webkit-app-region: drag;`

https://www.electronjs.org/docs/latest/api/frameless-window/#draggable-region

**Comment by kimlimjustin** [comment]
Could you please screen record what actually happens and could you please specify your OS? cuz it's just working fine for me, and I use the `-webkit-app-region: drag;` to enable dragging
https://github.com/kimlimjustin/xplorer/blob/master/src/Components/Layout/layout.scss#L105

In addition, for Windows, I'm using [`electron-acrylic-window`](https://www.npmjs.com/package/electron-acrylic-window) to support the acrylic effect, please try clone the repo example, does it occurs on that? If it does, then it's the problem, I'll add setting option to use electron's BrowserWindow instead of the package.

**Comment by 4lenz1** [comment]
I got same problem on windows 10 pro 20H2
i'm using trackball so it might a little bit difficult to see my finger movement.
but you can see that the xplorer's window still moving after my finger stopped (at 0:10) while the default explorer not.

https://user-images.githubusercontent.com/5239389/134838406-7e151ad4-7e6a-4987-bf6f-ae64f711ea1f.mp4

**Comment by Profesor08** [comment]
> Could you please screen record what actually happens and could you please specify your OS? cuz it's just working fine for me, and I use the `-webkit-app-region: drag;` to enable dragging

OS: Win10

Video not showing the effect, not enough fps to see effect, and it not showing the input lag between mouse move on the table and screen reaction.

If I make window bigger, the lag is bigger. If I move window ~5 sec and relese, I see 2 cursors, first is stil moving with window, second is system xD


> In addition, for Windows, I'm using [`electron-acrylic-window`](https://www.npmjs.com/package/electron-acrylic-window) to support the acrylic effect, please try clone the repo example, does it occurs on that? If it does, then it's the problem, I'll add setting option to use electron's BrowserWindow instead of the package.

I can't install packages for both repo's xD, it fails on node-gyp, because it want Visual Studio to be installed. WTF if this is 
 crossplatfor tool? Regular electron app not requires nothing to run and to work.

**Comment by kimlimjustin** [comment]
Okay, I'll add an option to use electron's browserwindow instead of  `electron-acrylic-window`'s.

> I can't install packages for both repo's xD, it fails on node-gyp, because it want Visual Studio to be installed. WTF if this is
crossplatfor tool? Regular electron app not requires nothing to run and to work.

Yes, underneath the hood, it checks what OS is, If it's Windows, then it will require VS C++ to compile some native windows 10 features such as the Acrylic effect and to parse icons from exe file, this feature only works and is only supported on Windows 10. If the OS is not windows, it does not require the VS C++ and can be run, but without the features I mentioned.

**Comment by Ponokefalos** [comment]
I had the same issue on my first installation (Windows 10) where in that time I had Xplorer and windows explorer open at the  same time. When I re-open the app the issue was fixed!

**Comment by Ponokefalos** [comment]
I just did a clean installation and I saw the same laggy issue. I can suggest a temp solution for anyone else who has the same issue. If you disable the acrylic `effect` from settings it will solve it. What do you think @kimlimjustin ?

**Comment by kimlimjustin** [comment]
> I just did a clean installation and I saw the same laggy issue. I can suggest a temp solution for anyone else who has the same issue. If you disable the acrylic `effect` from settings and then re-open the app it will solve it. What do you think @kimlimjustin ?

Ye, that's the way, I think we should just turn off vibrancy support for default (this will import Electron's BrowserWindow as default) and only enable it if the user enables it (will need to reopen the app to see the effect).

I'll update it soon, or do you want to contri ?

**Comment by Ponokefalos** [comment]
@kimlimjustin Sure I will submit a PR later today. I will try to add a note for users to inform them that if they enable this setting they need to restart the app to take effect. What do you thing about that?

**Comment by kimlimjustin** [comment]
Yeah sounds good!

**Comment by kimlimjustin** [comment]
Does this still occur on v0.2.0?

**Comment by kimlimjustin** [comment]
I'll close this issue because of inactivity, please open another issue if this issue still occurs on the latest version.
